site_name: GradsFlow AutoML
site_description: "GradsFlow Codeless Machine Learning"
banner_url: https://ik.imagekit.io/gradsflow/logo/logo_sA2Al0_Ph6Cc.png
repo_url: https://github.com/gradsflow/automl/
repo_name: gradsflow/automl

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo: https://ik.imagekit.io/gradsflow/logo/logo-small_g2MxLWesD.png?updatedAt=1627716948296
  favicon: https://ik.imagekit.io/gradsflow/favicon/favicon_7lEXKqKWxlD.ico
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized
  - search

extra:
  homepage: https://automl.gradsflow.com/en/latest/

nav:
  - Introduction: 'index.md'
